# _config.yml

# Site settings
title: Your Name - Data Engineering and Consulting
description: Data engineering and consulting services for the energy industry.

# Build settings
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-sitemap

# Navigation
navbar_links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Services
    url: /services
  - title: Projects
    url: /projects
  - title: Blog
    url: /blog

# Exclude files and directories from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Custom variables
energy_industry_skills:
  - Data Engineering
  - Data Analysis
  - Business Intelligence
  - Machine Learning
  - Consulting

# SEO settings
seo:
  type: website
  title: Your Name - Data Engineering and Consulting
  description: Data engineering and consulting services for the energy industry.
  image: IMG_0043.JPG
  github_username: andrewjeffallen
